// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// Target: library
// **************************************************************************

// Generated by owl 0.2.1
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'impl_models.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

// **************************************************************************
// Generator: JsonGenerator
// Target: class SteemResponse
// **************************************************************************

/// Mapper for SteemResponse
abstract class SteemResponseMapper {
  /// Converts an instance of SteemResponse to Map.
  static Map<String, dynamic> map(SteemResponse object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('meta', SteemExceptionMapper.map(object.meta))
          ..put('pagination',
              SteemResponsePaginationMapper.map(object.pagination))
          ..put('data', object.data))
        .toMap();
  }

  /// Converts a Map to an instance of SteemResponse.
  static SteemResponse parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SteemResponse object = new SteemResponse();
    object.meta = SteemExceptionMapper.parse(map['meta']);
    object.pagination = SteemResponsePaginationMapper.parse(map['pagination']);
    object.data = map['data'];
    return object;
  }

  /// Converts a JSON string to an instance of SteemResponse.
  static SteemResponse fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SteemResponse to JSON string.
  static String toJson(SteemResponse object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class SteemException
// **************************************************************************

/// Mapper for SteemException
abstract class SteemExceptionMapper {
  /// Converts an instance of SteemException to Map.
  static Map<String, dynamic> map(SteemException object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('error', object.error)
          ..put('error_description', object.errorDescription))
        .toMap();
  }

  /// Converts a Map to an instance of SteemException.
  static SteemException parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SteemException object = new SteemException();
    object.error = map['error'];
    object.errorDescription = map['error_description'];
    return object;
  }

  /// Converts a JSON string to an instance of SteemException.
  static SteemException fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SteemException to JSON string.
  static String toJson(SteemException object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class SteemResponsePagination
// **************************************************************************

/// Mapper for SteemResponsePagination
abstract class SteemResponsePaginationMapper {
  /// Converts an instance of SteemResponsePagination to Map.
  static Map<String, dynamic> map(SteemResponsePagination object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('entry_id', object.entryId))
        .toMap();
  }

  /// Converts a Map to an instance of SteemResponsePagination.
  static SteemResponsePagination parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SteemResponsePagination object = new SteemResponsePagination();
    object.entryId = map['entry_id'];
    return object;
  }

  /// Converts a JSON string to an instance of SteemResponsePagination.
  static SteemResponsePagination fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SteemResponsePagination to JSON string.
  static String toJson(SteemResponsePagination object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class SteemAuthException
// **************************************************************************

/// Mapper for SteemAuthException
abstract class SteemAuthExceptionMapper {
  /// Converts an instance of SteemAuthException to Map.
  static Map<String, dynamic> map(SteemAuthException object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('error', object.error)
          ..put('error_description', object.errorDescription))
        .toMap();
  }

  /// Converts a Map to an instance of SteemAuthException.
  static SteemAuthException parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final SteemAuthException object = new SteemAuthException();
    object.error = map['error'];
    object.errorDescription = map['error_description'];
    return object;
  }

  /// Converts a JSON string to an instance of SteemAuthException.
  static SteemAuthException fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of SteemAuthException to JSON string.
  static String toJson(SteemAuthException object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
