// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// Target: library
// **************************************************************************

// Generated by owl 0.2.1
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'models.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

// **************************************************************************
// Generator: JsonGenerator
// Target: class AccessTokenResponse
// **************************************************************************

/// Mapper for AccessTokenResponse
abstract class AccessTokenResponseMapper {
  /// Converts an instance of AccessTokenResponse to Map.
  static Map<String, dynamic> map(AccessTokenResponse object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('access_token', object.accessToken)
          ..put('user', UserMapper.map(object.user)))
        .toMap();
  }

  /// Converts a Map to an instance of AccessTokenResponse.
  static AccessTokenResponse parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final AccessTokenResponse object = new AccessTokenResponse();
    object.accessToken = map['access_token'];
    object.user = UserMapper.parse(map['user']);
    return object;
  }

  /// Converts a JSON string to an instance of AccessTokenResponse.
  static AccessTokenResponse fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of AccessTokenResponse to JSON string.
  static String toJson(AccessTokenResponse object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class User
// **************************************************************************

/// Mapper for User
abstract class UserMapper {
  /// Converts an instance of User to Map.
  static Map<String, dynamic> map(User object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('id', object.id)
          ..put('proxy', object.proxy)
          ..put('balance', object.balance)
          ..put('created', _owl_json.DateTimeMapper.map(object.created))
          ..put('mined', object.mined)
          ..put('withdrawn', object.withdrawn)
          ..put('name', object.username)
          ..put('memo_key', object.memoKey)
          ..put('json_metadata', object.jsonMetadata)
          ..put('last_owner_update',
              _owl_json.DateTimeMapper.map(object.lastOwnerUpdate))
          ..put('last_account_update',
              _owl_json.DateTimeMapper.map(object.lastAccountUpdate))
          ..put('owner_challenged', object.ownerChallenged)
          ..put('active_challenged', object.activeChallenged)
          ..put('last_owner_proved',
              _owl_json.DateTimeMapper.map(object.lastOwnerProved))
          ..put('last_active_proved',
              _owl_json.DateTimeMapper.map(object.lastActiveProved))
          ..put('recovery_account', object.recoveryAccount)
          ..put('last_account_recovery',
              _owl_json.DateTimeMapper.map(object.lastAccountRecovery))
          ..put('reset_account', object.resetAccount)
          ..put('comment_count', object.commentCount)
          ..put('lifetime_vote_count', object.lifetimeVoteCount)
          ..put('post_count', object.postCount)
          ..put('can_vote', object.canVote)
          ..put('voting_power', object.votingPower)
          ..put('last_vote_time',
              _owl_json.DateTimeMapper.map(object.lastVoteTime))
          ..put('savings_balance', object.savingsBalance)
          ..put('sbd_balance', object.sbdBalance)
          ..put('sbd_seconds', object.sbdSeconds)
          ..put('sbd_seconds_last_update',
              _owl_json.DateTimeMapper.map(object.sbdSecondsLastUpdate))
          ..put('sbd_last_interest_payment',
              _owl_json.DateTimeMapper.map(object.sbdLastInterestPayment))
          ..put('savings_sbd_balance', object.savingsSbdBalance)
          ..put('savings_sbd_seconds', object.savingsSbdSeconds)
          ..put('savings_sbd_seconds_last_update',
              _owl_json.DateTimeMapper.map(object.savingsSbdSecondsLastUpdate))
          ..put(
              'savings_sbd_last_interest_payment',
              _owl_json.DateTimeMapper
                  .map(object.savingsSbdLastInterestPayment))
          ..put('savings_withdraw_requests', object.savingsWithdrawRequests)
          ..put('reward_sbd_balance', object.rewardSbdBalance)
          ..put('reward_steem_balance', object.rewardSteemBalance)
          ..put('reward_vesting_balance', object.rewardVestingBalance)
          ..put('reward_vesting_steem', object.rewardVestingSteem)
          ..put('vesting_shares', object.vestingShares)
          ..put('delegated_vesting_shares', object.delegatedVestingShares)
          ..put('received_vesting_shares', object.receivedVestingShares)
          ..put('vesting_withdraw_rate', object.vestingWithdrawRate)
          ..put('next_vesting_withdrawal',
              _owl_json.DateTimeMapper.map(object.nextVestingWithdrawal))
          ..put('to_withdraw', object.toWithdraw)
          ..put('withdraw_routes', object.withdrawRoutes)
          ..put('curation_rewards', object.curationRewards)
          ..put('posting_rewards', object.postingRewards)
          ..put('proxied_vsf_votes', object.proxiedVsfVotes?.toList())
          ..put('witnesses_voted_for', object.witnessesVotedFor)
          ..put('average_bandwith', object.averageBandwith)
          ..put('lifetime_bandwith', object.lifetimeBandwith)
          ..put('last_bandwith_update',
              _owl_json.DateTimeMapper.map(object.lastBandwithUpdate))
          ..put('average_market_bandwith', object.averageMarketBandwith)
          ..put('lifetime_market_bandwith', object.lifetimeMarketBandwith)
          ..put('last_market_bandwith_update',
              _owl_json.DateTimeMapper.map(object.lastMarketBandwithUpdate))
          ..put('last_post', _owl_json.DateTimeMapper.map(object.lastPost))
          ..put('last_root_post',
              _owl_json.DateTimeMapper.map(object.lastRootPost))
          ..put('vesting_balance', object.vestingBalance)
          ..put('reputation', object.reputation))
        .toMap();
  }

  /// Converts a Map to an instance of User.
  static User parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final User object = new User();
    object.id = map['id'];
    object.proxy = map['proxy'];
    object.balance = map['balance'];
    object.created = _owl_json.DateTimeMapper.parse(map['created']);
    object.mined = map['mined'];
    object.withdrawn = map['withdrawn'];
    object.username = map['name'];
    object.memoKey = map['memo_key'];
    object.jsonMetadata = map['json_metadata'];
    object.lastOwnerUpdate =
        _owl_json.DateTimeMapper.parse(map['last_owner_update']);
    object.lastAccountUpdate =
        _owl_json.DateTimeMapper.parse(map['last_account_update']);
    object.ownerChallenged = map['owner_challenged'];
    object.activeChallenged = map['active_challenged'];
    object.lastOwnerProved =
        _owl_json.DateTimeMapper.parse(map['last_owner_proved']);
    object.lastActiveProved =
        _owl_json.DateTimeMapper.parse(map['last_active_proved']);
    object.recoveryAccount = map['recovery_account'];
    object.lastAccountRecovery =
        _owl_json.DateTimeMapper.parse(map['last_account_recovery']);
    object.resetAccount = map['reset_account'];
    object.commentCount = map['comment_count'];
    object.lifetimeVoteCount = map['lifetime_vote_count'];
    object.postCount = map['post_count'];
    object.canVote = map['can_vote'];
    object.votingPower = map['voting_power'];
    object.lastVoteTime = _owl_json.DateTimeMapper.parse(map['last_vote_time']);
    object.savingsBalance = map['savings_balance'];
    object.sbdBalance = map['sbd_balance'];
    object.sbdSeconds = map['sbd_seconds'];
    object.sbdSecondsLastUpdate =
        _owl_json.DateTimeMapper.parse(map['sbd_seconds_last_update']);
    object.sbdLastInterestPayment =
        _owl_json.DateTimeMapper.parse(map['sbd_last_interest_payment']);
    object.savingsSbdBalance = map['savings_sbd_balance'];
    object.savingsSbdSeconds = map['savings_sbd_seconds'];
    object.savingsSbdSecondsLastUpdate =
        _owl_json.DateTimeMapper.parse(map['savings_sbd_seconds_last_update']);
    object.savingsSbdLastInterestPayment = _owl_json.DateTimeMapper
        .parse(map['savings_sbd_last_interest_payment']);
    object.savingsWithdrawRequests = map['savings_withdraw_requests'];
    object.rewardSbdBalance = map['reward_sbd_balance'];
    object.rewardSteemBalance = map['reward_steem_balance'];
    object.rewardVestingBalance = map['reward_vesting_balance'];
    object.rewardVestingSteem = map['reward_vesting_steem'];
    object.vestingShares = map['vesting_shares'];
    object.delegatedVestingShares = map['delegated_vesting_shares'];
    object.receivedVestingShares = map['received_vesting_shares'];
    object.vestingWithdrawRate = map['vesting_withdraw_rate'];
    object.nextVestingWithdrawal =
        _owl_json.DateTimeMapper.parse(map['next_vesting_withdrawal']);
    object.toWithdraw = map['to_withdraw'];
    object.withdrawRoutes = map['withdraw_routes'];
    object.curationRewards = map['curation_rewards'];
    object.postingRewards = map['posting_rewards'];

    // ignore: avoid_as
    object.proxiedVsfVotes = (map['proxied_vsf_votes'] as List<int>)?.toList();
    object.witnessesVotedFor = map['witnesses_voted_for'];
    object.averageBandwith = map['average_bandwith'];
    object.lifetimeBandwith = map['lifetime_bandwith'];
    object.lastBandwithUpdate =
        _owl_json.DateTimeMapper.parse(map['last_bandwith_update']);
    object.averageMarketBandwith = map['average_market_bandwith'];
    object.lifetimeMarketBandwith = map['lifetime_market_bandwith'];
    object.lastMarketBandwithUpdate =
        _owl_json.DateTimeMapper.parse(map['last_market_bandwith_update']);
    object.lastPost = _owl_json.DateTimeMapper.parse(map['last_post']);
    object.lastRootPost = _owl_json.DateTimeMapper.parse(map['last_root_post']);
    object.vestingBalance = map['vesting_balance'];
    object.reputation = map['reputation'];
    return object;
  }

  /// Converts a JSON string to an instance of User.
  static User fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of User to JSON string.
  static String toJson(User object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Followers
// **************************************************************************

/// Mapper for Followers
abstract class FollowersMapper {
  /// Converts an instance of Followers to Map.
  static Map<String, dynamic> map(Followers object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('follower', object.follower)
          ..put('following', object.following)
          ..put('what', object.what))
        .toMap();
  }

  /// Converts a Map to an instance of Followers.
  static Followers parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Followers object = new Followers();
    object.follower = map['follower'];
    object.following = map['following'];
    object.what = map['what'];
    return object;
  }

  /// Converts a JSON string to an instance of Followers.
  static Followers fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Followers to JSON string.
  static String toJson(Followers object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Post
// **************************************************************************

/// Mapper for Post
abstract class PostMapper {
  /// Converts an instance of Post to Map.
  static Map<String, dynamic> map(Post object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('id', object.id)
          ..put('author', object.author)
          ..put('permlink', object.permlink)
          ..put('category', object.category)
          ..put('title', object.title)
          ..put('body', object.body)
          ..put('blog', object.blog)
          ..put('created', _owl_json.DateTimeMapper.map(object.created))
          ..put('active', _owl_json.DateTimeMapper.map(object.active))
          ..put('depth', object.depth)
          ..put('children', object.children)
          ..put('vote', object.vote)
          ..put('flag', object.flag)
          ..put('isNSFW', object.isNSFW)
          ..put('tags', object.tags?.toList())
          ..put('parent_author', object.parentAuthor)
          ..put('parent_permlink', object.parentPermlink)
          ..put('json_metadata', object.jsonMetadata)
          ..put('last_update', _owl_json.DateTimeMapper.map(object.lastUpdate))
          ..put('last_payout', _owl_json.DateTimeMapper.map(object.lastPayout))
          ..put('net_rshares', object.netRShares)
          ..put('abs_rshares', object.absRShares)
          ..put('vote_rshares', object.voteRShares)
          ..put('children_abs_rshares', object.childrenAbsRShares)
          ..put(
              'cashout_time', _owl_json.DateTimeMapper.map(object.cashoutTime))
          ..put('max_cashout_time',
              _owl_json.DateTimeMapper.map(object.maxCashoutTime))
          ..put('total_vote_weight', object.totalVoteWeight)
          ..put('reward_weight', object.rewardWeight)
          ..put('total_payout_value', object.totalPayoutValue)
          ..put('curator_payout_value', object.curatorPayoutValue)
          ..put('author_rewards', object.authorRewards)
          ..put('net_votes', object.netVotes)
          ..put('root_comment', object.rootComment)
          ..put('max_accepted_payout', object.maxAcceptedPayout)
          ..put('percent_steem_dollars', object.percentSteemDollars)
          ..put('allow_replies', object.allowReplies)
          ..put('allow_votes', object.allowVotes)
          ..put('allow_curation_rewards', object.allowCurationRewards)
          ..put('beneficiaries', object.beneficiaries?.toList())
          ..put('reblog_on', _owl_json.DateTimeMapper.map(object.reblogOn))
          ..put('reblog_by', object.reblogBy?.toList())
          ..put('entry_id', object.entryId))
        .toMap();
  }

  /// Converts a Map to an instance of Post.
  static Post parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Post object = new Post();
    object.id = map['id'];
    object.author = map['author'];
    object.permlink = map['permlink'];
    object.category = map['category'];
    object.title = map['title'];
    object.body = map['body'];
    object.blog = map['blog'];
    object.created = _owl_json.DateTimeMapper.parse(map['created']);
    object.active = _owl_json.DateTimeMapper.parse(map['active']);
    object.depth = map['depth'];
    object.children = map['children'];
    object.vote = map['vote'];
    object.flag = map['flag'];
    object.isNSFW = map['isNSFW'];

    // ignore: avoid_as
    object.tags = (map['tags'] as List<String>)?.toList();
    object.parentAuthor = map['parent_author'];
    object.parentPermlink = map['parent_permlink'];
    object.jsonMetadata = map['json_metadata'];
    object.lastUpdate = _owl_json.DateTimeMapper.parse(map['last_update']);
    object.lastPayout = _owl_json.DateTimeMapper.parse(map['last_payout']);
    object.netRShares = map['net_rshares'];
    object.absRShares = map['abs_rshares'];
    object.voteRShares = map['vote_rshares'];
    object.childrenAbsRShares = map['children_abs_rshares'];
    object.cashoutTime = _owl_json.DateTimeMapper.parse(map['cashout_time']);
    object.maxCashoutTime =
        _owl_json.DateTimeMapper.parse(map['max_cashout_time']);
    object.totalVoteWeight = map['total_vote_weight'];
    object.rewardWeight = map['reward_weight'];
    object.totalPayoutValue = map['total_payout_value'];
    object.curatorPayoutValue = map['curator_payout_value'];
    object.authorRewards = map['author_rewards'];
    object.netVotes = map['net_votes'];
    object.rootComment = map['root_comment'];
    object.maxAcceptedPayout = map['max_accepted_payout'];
    object.percentSteemDollars = map['percent_steem_dollars'];
    object.allowReplies = map['allow_replies'];
    object.allowVotes = map['allow_votes'];
    object.allowCurationRewards = map['allow_curation_rewards'];

    // ignore: avoid_as
    object.beneficiaries = (map['beneficiaries'] as List<String>)?.toList();
    object.reblogOn = _owl_json.DateTimeMapper.parse(map['reblog_on']);

    // ignore: avoid_as
    object.reblogBy = (map['reblog_by'] as List<String>)?.toList();
    object.entryId = map['entry_id'];
    return object;
  }

  /// Converts a JSON string to an instance of Post.
  static Post fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Post to JSON string.
  static String toJson(Post object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Reply
// **************************************************************************

/// Mapper for Reply
abstract class ReplyMapper {
  /// Converts an instance of Reply to Map.
  static Map<String, dynamic> map(Reply object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('id', object.id)
          ..put('author', object.author)
          ..put('permlink', object.permlink)
          ..put('category', object.category)
          ..put('title', object.title)
          ..put('body', object.body)
          ..put('url', object.url)
          ..put('promoted', object.promoted)
          ..put('created', _owl_json.DateTimeMapper.map(object.created))
          ..put('active', _owl_json.DateTimeMapper.map(object.active))
          ..put('depth', object.depth)
          ..put('children', object.children)
          ..put('beneficiaries',
              object.beneficiaries?.map(BeneficiaryMapper.map)?.toList())
          ..put('replies', object.replies?.map(ReplyMapper.map)?.toList())
          ..put('parent_author', object.parentAuthor)
          ..put('parent_permlink', object.parentPermlink)
          ..put('json_metadata', object.jsonMetadata)
          ..put('last_update', _owl_json.DateTimeMapper.map(object.lastUpdate))
          ..put('last_payout', _owl_json.DateTimeMapper.map(object.lastPayout))
          ..put('net_rshares', object.netRShares)
          ..put('abs_rshares', object.absRShares)
          ..put('vote_rshares', object.voteRShares)
          ..put('children_abs_rshares', object.childrenAbsRShares)
          ..put(
              'cashout_time', _owl_json.DateTimeMapper.map(object.cashoutTime))
          ..put('max_cashout_time',
              _owl_json.DateTimeMapper.map(object.maxCashoutTime))
          ..put('total_vote_weight', object.totalVoteWeight)
          ..put('reward_weight', object.rewardWeight)
          ..put('total_payout_value', object.totalPayoutValue)
          ..put('curator_payout_value', object.curatorPayoutValue)
          ..put('author_rewards', object.authorRewards)
          ..put('net_votes', object.netVotes)
          ..put('root_comment', object.rootComment)
          ..put('max_accepted_payout', object.maxAcceptedPayout)
          ..put('percent_steem_dollars', object.percentSteemDollars)
          ..put('allow_replies', object.allowReplies)
          ..put('allow_votes', object.allowVotes)
          ..put('allow_curation_rewards', object.allowCurationRewards)
          ..put('root_title', object.rootTitle)
          ..put('pending_payout_value', object.pendingPayoutValue)
          ..put('total_pending_payout_value', object.totalPendingPayoutValue)
          ..put('active_votes',
              object.activeVotes?.map(ActiveVoteMapper.map)?.toList())
          ..put('author_reputation', object.authorReputation)
          ..put('body_length', object.bodyLength)
          ..put('reblogged_by', object.rebloggedBy?.toList()))
        .toMap();
  }

  /// Converts a Map to an instance of Reply.
  static Reply parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Reply object = new Reply();
    object.id = map['id'];
    object.author = map['author'];
    object.permlink = map['permlink'];
    object.category = map['category'];
    object.title = map['title'];
    object.body = map['body'];
    object.url = map['url'];
    object.promoted = map['promoted'];
    object.created = _owl_json.DateTimeMapper.parse(map['created']);
    object.active = _owl_json.DateTimeMapper.parse(map['active']);
    object.depth = map['depth'];
    object.children = map['children'];

    // ignore: avoid_as
    object.beneficiaries = (map['beneficiaries'] as List<dynamic>)
        ?.map(BeneficiaryMapper.parse)
        ?.toList();

    // ignore: avoid_as
    object.replies =
        (map['replies'] as List<dynamic>)?.map(ReplyMapper.parse)?.toList();
    object.parentAuthor = map['parent_author'];
    object.parentPermlink = map['parent_permlink'];
    object.jsonMetadata = map['json_metadata'];
    object.lastUpdate = _owl_json.DateTimeMapper.parse(map['last_update']);
    object.lastPayout = _owl_json.DateTimeMapper.parse(map['last_payout']);
    object.netRShares = map['net_rshares'];
    object.absRShares = map['abs_rshares'];
    object.voteRShares = map['vote_rshares'];
    object.childrenAbsRShares = map['children_abs_rshares'];
    object.cashoutTime = _owl_json.DateTimeMapper.parse(map['cashout_time']);
    object.maxCashoutTime =
        _owl_json.DateTimeMapper.parse(map['max_cashout_time']);
    object.totalVoteWeight = map['total_vote_weight'];
    object.rewardWeight = map['reward_weight'];
    object.totalPayoutValue = map['total_payout_value'];
    object.curatorPayoutValue = map['curator_payout_value'];
    object.authorRewards = map['author_rewards'];
    object.netVotes = map['net_votes'];
    object.rootComment = map['root_comment'];
    object.maxAcceptedPayout = map['max_accepted_payout'];
    object.percentSteemDollars = map['percent_steem_dollars'];
    object.allowReplies = map['allow_replies'];
    object.allowVotes = map['allow_votes'];
    object.allowCurationRewards = map['allow_curation_rewards'];
    object.rootTitle = map['root_title'];
    object.pendingPayoutValue = map['pending_payout_value'];
    object.totalPendingPayoutValue = map['total_pending_payout_value'];

    // ignore: avoid_as
    object.activeVotes = (map['active_votes'] as List<dynamic>)
        ?.map(ActiveVoteMapper.parse)
        ?.toList();
    object.authorReputation = map['author_reputation'];
    object.bodyLength = map['body_length'];

    // ignore: avoid_as
    object.rebloggedBy = (map['reblogged_by'] as List<String>)?.toList();
    return object;
  }

  /// Converts a JSON string to an instance of Reply.
  static Reply fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Reply to JSON string.
  static String toJson(Reply object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class ActiveVote
// **************************************************************************

/// Mapper for ActiveVote
abstract class ActiveVoteMapper {
  /// Converts an instance of ActiveVote to Map.
  static Map<String, dynamic> map(ActiveVote object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('voter', object.voter)
          ..put('rshares', object.rshares)
          ..put('reputation', object.reputation)
          ..put('weight', object.weight)
          ..put('percent', object.percent)
          ..put('time', _owl_json.DateTimeMapper.map(object.time)))
        .toMap();
  }

  /// Converts a Map to an instance of ActiveVote.
  static ActiveVote parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ActiveVote object = new ActiveVote();
    object.voter = map['voter'];
    object.rshares = map['rshares'];
    object.reputation = map['reputation'];
    object.weight = map['weight'];
    object.percent = map['percent'];
    object.time = _owl_json.DateTimeMapper.parse(map['time']);
    return object;
  }

  /// Converts a JSON string to an instance of ActiveVote.
  static ActiveVote fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ActiveVote to JSON string.
  static String toJson(ActiveVote object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class PostVote
// **************************************************************************

/// Mapper for PostVote
abstract class PostVoteMapper {
  /// Converts an instance of PostVote to Map.
  static Map<String, dynamic> map(PostVote object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('authorperm', object.authorperm)
          ..put('weight', object.weight)
          ..put('rshares', object.rshares)
          ..put('percent', object.percent)
          ..put('time', _owl_json.DateTimeMapper.map(object.time)))
        .toMap();
  }

  /// Converts a Map to an instance of PostVote.
  static PostVote parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final PostVote object = new PostVote();
    object.authorperm = map['authorperm'];
    object.weight = map['weight'];
    object.rshares = map['rshares'];
    object.percent = map['percent'];
    object.time = _owl_json.DateTimeMapper.parse(map['time']);
    return object;
  }

  /// Converts a JSON string to an instance of PostVote.
  static PostVote fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of PostVote to JSON string.
  static String toJson(PostVote object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Tag
// **************************************************************************

/// Mapper for Tag
abstract class TagMapper {
  /// Converts an instance of Tag to Map.
  static Map<String, dynamic> map(Tag object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('name', object.name)
          ..put('trending', object.trending)
          ..put('comments', object.comments)
          ..put('total_payouts', object.totalPayouts)
          ..put('net_votes', object.netVotes)
          ..put('top_posts', object.topPosts))
        .toMap();
  }

  /// Converts a Map to an instance of Tag.
  static Tag parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Tag object = new Tag();
    object.name = map['name'];
    object.trending = map['trending'];
    object.comments = map['comments'];
    object.totalPayouts = map['total_payouts'];
    object.netVotes = map['net_votes'];
    object.topPosts = map['top_posts'];
    return object;
  }

  /// Converts a JSON string to an instance of Tag.
  static Tag fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Tag to JSON string.
  static String toJson(Tag object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Relationship
// **************************************************************************

/// Mapper for Relationship
abstract class RelationshipMapper {
  /// Converts an instance of Relationship to Map.
  static Map<String, dynamic> map(Relationship object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('follower', object.follower)
          ..put('following', object.following)
          ..put('what', object.what?.toList()))
        .toMap();
  }

  /// Converts a Map to an instance of Relationship.
  static Relationship parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Relationship object = new Relationship();
    object.follower = map['follower'];
    object.following = map['following'];

    // ignore: avoid_as
    object.what = (map['what'] as List<String>)?.toList();
    return object;
  }

  /// Converts a JSON string to an instance of Relationship.
  static Relationship fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Relationship to JSON string.
  static String toJson(Relationship object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Beneficiary
// **************************************************************************

/// Mapper for Beneficiary
abstract class BeneficiaryMapper {
  /// Converts an instance of Beneficiary to Map.
  static Map<String, dynamic> map(Beneficiary object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('account', object.account)
          ..put('weight', object.weight))
        .toMap();
  }

  /// Converts a Map to an instance of Beneficiary.
  static Beneficiary parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Beneficiary object = new Beneficiary();
    object.account = map['account'];
    object.weight = map['weight'];
    return object;
  }

  /// Converts a JSON string to an instance of Beneficiary.
  static Beneficiary fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Beneficiary to JSON string.
  static String toJson(Beneficiary object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
